#code base constants
DEFAULT_CODE_BASE_CHUNK_SIZE = 60
DEFAULT_CODE_BASE_OVERLAP_SIZE = 0
DEFAULT_CODE_BASE_LANGUAGE = "javascript"

#doc constants
DEFAULT_DOC_CHUNK_SIZE = 500
DEFAULT_DOC_OVERLAP_SIZE = 100



